docs: add delivery options documentation
myparcelnl/developer pull request #6
Opened 2022-06-02 08:23 UTC by wthijmen

2022-06-02 12:56 UTC, EdieLemoine requested changes
formatting

2022-06-02 14:05 UTC, EdieLemoine requested changes

2022-06-02 14:05 UTC, EdieLemoine commented on src/documentation/60.delivery-options/10.usage-examples.md
> +window.MyParcelConfig = {
js moet met 2 spaties geindent worden, werkt die code style wel goed?

2022-06-09 14:56 UTC, Mark-Ernst approved these changes

2022-06-10 06:50 UTC, merged