docs(integrations): add etsy
myparcelnl/developer pull request #60
Opened 2023-05-15 12:43 UTC by RichardPerdaan

2023-05-15 12:44 UTC, wthijmen approved these changes

2023-05-15 14:03 UTC, EdieLemoine requested changes

2023-05-15 14:03 UTC, EdieLemoine commented on src/nl/documentatie/30.etsy.md
> +Om je orders van Etsy te importeren, klik je in het zendingenoverzicht op en dan op Upload Etsy orders. Selecteer je meest recente Etsy besteloverzicht. De orders zullen ingeladen worden. Nadat je op
```suggestion
Om je orders van Etsy te importeren, klik je in het zendingenoverzicht op "Importeer externe zendingen". Openstaande Etsy orders zullen ingeladen worden. Selecteer welke orders je wilt importeren en druk op "Importeren". Deze orders zullen als concepten in je zendingenoverzicht komen te staan.
```

2023-05-15 14:03 UTC, EdieLemoine commented on src/nl/documentatie/30.etsy.md
> +In de MyParcel backoffice wordt nu een terugkoppeling getoond van de Etsy koppeling
```suggestion
In de MyParcel Backoffice wordt nu een terugkoppeling getoond dat het koppelen met Etsy geslaagd is.
```

2023-05-15 14:03 UTC, EdieLemoine commented on src/nl/documentatie/30.etsy.md
> +Gebruik jouw Etsy login credentials om in te loggen en een connectie te maken tussen MyParcel en Etsy.
```suggestion
Log in bij Etsy en maak een connectie te tussen MyParcel en jouw webwinkel.
```

2023-05-15 14:03 UTC, EdieLemoine commented on src/nl/documentatie/30.etsy.md
> +### Etsy login
```suggestion
### Inloggen bij Etsy
```

2023-05-15 14:04 UTC, EdieLemoine requested changes

2023-06-05 14:13 UTC, RichardPerdaan commented on src/.vuepress/integrations.json
> +    "documentation": "/documentation/30.etsy.html",
Afgesproken met marketing

2023-06-05 14:28 UTC, RichardPerdaan commented on src/nl/documentatie/30.etsy.md
> +Navigeer in de MyParcel backoffice naar Shopinstellingen > Integratie en scroll naar Etsy. Klik op de button [Geef toestemming]
done

2023-06-05 14:28 UTC, RichardPerdaan commented on src/nl/documentatie/30.etsy.md
> +<MPImg src="/documentation/etsy/etsy_shopinstellingen_integratie.png" alt="Etsy integratie" />
Done

2023-06-05 14:33 UTC, Mark-Ernst approved these changes

2023-06-06 08:27 UTC, EdieLemoine requested changes

2023-06-06 08:27 UTC, EdieLemoine commented on src/nl/documentatie/30.etsy.md
> +Navigeer in de MyParcel backoffice naar [Shopinstellingen > Integratie](https://backoffice.myparcel.nl/settings/integration) en scroll naar Etsy. Klik op de button [Geef toestemming]
```suggestion
Navigeer in de MyParcel Backoffice naar [Shopinstellingen > Integratie](https://backoffice.myparcel.nl/settings/integration) en scroll naar Etsy. Klik op de button "Geef toestemming"
```

2023-06-06 08:27 UTC, EdieLemoine commented on src/nl/documentatie/30.etsy.md
> +Je zendingen worden geïmporteerd als standaardzending. Welk pakkettype een standaardzending heeft, kun je instellen in je [backoffice bij > Shopinstellingen > Zendingen.](https://backoffice.myparcel.
```suggestion
Je zendingen worden geïmporteerd als standaardzending. Welk pakkettype een standaardzending heeft, kun je instellen in je MyParcel Backoffice bij > [Shopinstellingen > Zendingen](https://backoffice.myparcel.nl/settings/shipment).
```

2023-06-06 08:27 UTC, EdieLemoine commented on src/nl/documentatie/30.etsy.md
> +_Ja, de barcodes zullen teruggekoppeld worden aan Etsy en de bestelling zal de status "verzonden" krijgen zodra het label geprint is._
```suggestion
_Ja, de barcodes worden teruggekoppeld aan Etsy en de bestelling zal de status "verzonden" krijgen zodra het label geprint is._
```

2023-06-06 08:27 UTC, EdieLemoine approved these changes

2023-06-19 14:20 UTC, merged