docs: Update docs due to increased rate limits
myparcelnl/developer pull request #67
Opened 2023-06-28 11:48 UTC by Remco-Suiker

Increase rate limit to 300/5min for these endpoints:
- /delivery_options
- /pickup_locations
- /return_shipments
- /tracktraces/{ids?}

2023-06-28 12:11 UTC, Yogarine approved these changes

2023-06-29 13:57 UTC, EdieLemoine requested changes

2023-06-29 13:57 UTC, EdieLemoine commented on src/api-reference/08.delivery-options.md
> -This endpoint has a rate limit. For more information, see <ApiLink to="1_D">rate limiting</ApiLink>.
waarom is dit weg? er zit toch nog steeds een rate limit op?

2023-06-29 14:03 UTC, EdieLemoine approved these changes

2023-06-29 14:06 UTC, merged