fix: add integrations url
myparcelnl/developer pull request #80
Opened 2023-09-29 07:45 UTC by wthijmen

2023-09-29 07:50 UTC, EdieLemoine requested changes
dit is geen `fix`, en kan je nadenken over een duidelijkere commit titel?

2023-09-29 07:50 UTC, EdieLemoine commented on src/.vuepress/integrations.json
> +    "url": ""
dit moet je gewoon kunnen weglaten als er geen url is

2023-09-29 07:50 UTC, EdieLemoine commented on src/.vuepress/theme/client/components/global/Integration.vue
> +        <AutoLink :item="`${data.url}`">
dit kan gewoon `data.url` zijn

2023-09-29 07:50 UTC, EdieLemoine commented on src/.vuepress/theme/client/components/global/Integration.vue
> +        <AutoLink :item="`${data.url}`">
de link moet niet gerendered worden als er geen link is

2023-09-29 09:55 UTC, Mark-Ernst approved these changes

2023-09-29 11:09 UTC, DevFrenk requested changes

2023-09-29 11:09 UTC, DevFrenk commented on src/.vuepress/integrations.json
> +    "url": "https://afosto.com/nl/docs/apps/myparcel/"
Het is hier, maar ook op andere plekken, de bedoeling dat de link achter documentation verwijst naar de documentatie over de MyParcel koppeling en als je op de 'tegel' klikt deze doorlinkt naar de homepage van de betreffende partij. In dit geval dus https://afosto.com

2023-09-29 11:33 UTC, DevFrenk requested changes

2023-09-29 11:33 UTC, DevFrenk commented on src/.vuepress/integrations.json
> +    "url": "https://sherpaan.nl"
Waarom staat soms wel en soms niet een eindslash?

2023-09-29 11:41 UTC, DevFrenk approved these changes

2023-09-29 11:47 UTC, EdieLemoine approved these changes

2023-09-29 11:47 UTC, Mark-Ernst approved these changes

2023-09-29 11:48 UTC, EdieLemoine requested changes

2023-09-29 11:48 UTC, EdieLemoine commented on src/.vuepress/theme/client/components/global/MPImg.vue
> +    <component
dit werkt niet, het moet een AutoLink zijn

2023-09-29 11:48 UTC, EdieLemoine commented on src/.vuepress/integrations.json
> +    "url": "https://github.com/myparcelnl/cs-cart"
die github links zijn niet nodig

2023-09-29 11:48 UTC, EdieLemoine commented on src/.vuepress/theme/client/components/global/MPImg.vue
> +    <component
voeg dat Fragment component toe wat ik je liet zien

2023-10-12 08:17 UTC, EdieLemoine approved these changes

2023-10-12 08:22 UTC, merged